export enum SocketEvents {
  UserCount = "USER_COUNT",
  UserJoined = "USER_JOINED",
  UserLeft = "USER_LEFT",
  SendMessage = "SEND_MESSAGE",
  ReceiveMessage = "RECEIVE_MESSAGE",
  JoinRoom = "JOIN_ROOM",
  LeaveRoom = "LEAVE_ROOM",
  Authenticate = "AUTHENTICATE",
  Connect = "CONNECT",
  ConnectError = "CONNECT_ERROR",
  Disconnect = "DISCONNECT",
  ReconnectFailed = "RECONNECT_FAILED",
  Message = "MESSAGE",
  MessageReceived = "MESSAGE_RECEIVED",
  MessageHistory = "MESSAGE_HISTORY",
  SystemMessage = "SYSTEM_MESSAGE",
  NewMessage = "NEW_MESSAGE",
}
